### ISSUE TITLE
HP potencially critical bug

### ISSUE THREAD

**Issue by samples01010** [mat-os/Airplane#1]
Спасибо за ишью. Отвечу взаимностью. =)
Не стоит так делать. 
        if (hp == 0)
Если урон будет больше 1, то получите бессмертие.
Вообще подобные проверки всегда надо писать предвосхищая потенциальные ошибки, учитывая в них значения, которые не могут быть физически(в данном случае кол-во жизней не бывает отрицательным). Поэтому только так, и всегда только так.
     if (hp <= 0)

**Comment by mat-os** [comment]
Ох, спасибо, мой косяк, учту :3
